ok: str = "OK"
collection_complete: str = "collection complete"
interpolation_complete: str = "interpolation complete"
fine_dust_prediction_request: str = "fine dust prediction request"
fine_dust_prediction_complete: str = "fine dust prediction complete"
